// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyByKvLId8fBvWEHxtPoXk7exQLNry6CrYc',
    appId: '1:971233495843:web:4f742a60be37ca2f395a96',
    messagingSenderId: '971233495843',
    projectId: 'cleanbee-debe2',
    authDomain: 'cleanbee-debe2.firebaseapp.com',
    storageBucket: 'cleanbee-debe2.firebasestorage.app',
    measurementId: 'G-HJG8G1XT7G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBVQNT70qKQxZIzHNAZIBimA5c0ck1I0Sw',
    appId: '1:971233495843:android:115b49da9bfc2132395a96',
    messagingSenderId: '971233495843',
    projectId: 'cleanbee-debe2',
    storageBucket: 'cleanbee-debe2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDbrYtOP3aSqAP8bE0bDVhUqa0zyyLvEgg',
    appId: '1:971233495843:ios:8d8ea61fc08b439a395a96',
    messagingSenderId: '971233495843',
    projectId: 'cleanbee-debe2',
    storageBucket: 'cleanbee-debe2.firebasestorage.app',
    iosBundleId: 'com.example.cleanbee',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDbrYtOP3aSqAP8bE0bDVhUqa0zyyLvEgg',
    appId: '1:971233495843:ios:8d8ea61fc08b439a395a96',
    messagingSenderId: '971233495843',
    projectId: 'cleanbee-debe2',
    storageBucket: 'cleanbee-debe2.firebasestorage.app',
    iosBundleId: 'com.example.cleanbee',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyByKvLId8fBvWEHxtPoXk7exQLNry6CrYc',
    appId: '1:971233495843:web:4171177b199e98d4395a96',
    messagingSenderId: '971233495843',
    projectId: 'cleanbee-debe2',
    authDomain: 'cleanbee-debe2.firebaseapp.com',
    storageBucket: 'cleanbee-debe2.firebasestorage.app',
    measurementId: 'G-3RBX40JQ4H',
  );

}